name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Find and test all projects
      run: |
        for dir in */; do
          if [ -f "${dir}Cargo.toml" ]; then
            echo "Testing project in ${dir}"
            cd "${dir}"
            cargo build --verbose
            cargo test --verbose
            cargo clippy --verbose
            cd ..
          fi
        done
